# -*- coding: utf-8 -*-
"""Ejemplo_IPYWIDGETS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yp2uJ3x19sug9v_YoLPzHm-yz8clYxaX
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Asegúrate de estar en la carpeta principal de tu Colab
# %cd /content

# 2. Inicializa la carpeta como un repositorio de Git (esto creará la carpeta oculta .git)
!git init

# 3. Configura tu identidad (si no lo habías hecho antes)
!git config --global user.name "Profesor.Arredondo.IFAE"
!git config --global user.email "tu_email@ejemplo.com"

# 4. Agrega todos los archivos de tu proyecto
!git add .

# 5. Haz el primer registro (commit) local
!git commit -m "Primer commit desde Colab"

# 6. Nombra la rama como 'main'
!git branch -M main

# Commented out IPython magic to ensure Python compatibility.
import os

# 1. Define el nombre EXACTO de tu carpeta.
# Si tu carpeta tiene un espacio en medio, ponlo exactamente igual aquí:
CARPETA = "proyectoGPO05"

# %cd /content

# 2. Eliminamos el archivo .git oculto DENTRO de tu carpeta (el que causa el conflicto)
!rm -rf "{CARPETA}/.git"

# 3. Quitamos la carpeta del "índice" o memoria de Git (esto NO borra tus archivos reales)
!git rm --cached -r "{CARPETA}"

# 4. Volvemos a agregar la carpeta de forma correcta para que lea todos los archivos internos
!git add "{CARPETA}"

# 5. Registramos el cambio
!git commit -m "Corregido problema de carpeta inaccesible (submódulo)"

# 6. Forzamos la subida a GitHub
!git push -f origin main

# 1. Tus datos de configuración
TOKEN = ""
USUARIO = "profesoraarredondoifae-cell"
REPOSITORIO = "IFAE_GPO05"

# 2. Borramos cualquier rastro de configuración oculta de Git anterior en esta carpeta
!rm -rf .git

# 3. Inicializamos el repositorio desde cero
!git init
!git config --global user.name "{USUARIO}"
!git config --global user.email "profesor.aarredondo.ifae@gmail.com"

# 4. Agregamos los archivos y creamos el commit local
!git add .
!git commit -m "Commit limpio desde Google Colab"
!git branch -M main

# 5. Vinculamos el repositorio remoto usando la sintaxis explícita de Colab {variable}
!git remote add origin https://{TOKEN}@github.com/{USUARIO}/{REPOSITORIO}.git

# 1. Registramos el nuevo README.md (y cualquier otro cambio reciente)
!git add .
!git commit -m "Proyecto completo con README incluido"

# 2. Forzamos la subida para reemplazar el contenido en GitHub
!git push -f origin main

from ipywidgets import interact, IntSlider
from IPython.display import display

def saludar(nombre):
    print(f"¡Hola, {nombre}!")

# Crear un widget interactivo con un cuadro de texto
interact(saludar, nombre='Mundo');

"""También puedes crear controles deslizantes o botones para interactuar con tus datos o funciones:"""

def multiplicar(a, b):
    print(f"El resultado es: {a * b}")

# Crear dos controles deslizantes interactivos
interact(multiplicar, a=IntSlider(min=0, max=10, step=1, value=5), b=IntSlider(min=0, max=10, step=1, value=5));

"""## Tutorial de Análisis de Datos Interactivo con `ipywidgets`

`ipywidgets` es una librería que nos permite crear controles de interfaz de usuario (como deslizadores, casillas de verificación, botones, menús desplegables, etc.) directamente en nuestros notebooks de Colab o Jupyter. Esto es increíblemente útil para hacer que el análisis de datos sea interactivo y dinámico, permitiéndonos explorar diferentes escenarios sin tener que modificar y ejecutar celdas de código repetidamente.

### Paso 1: Cargar los Datos

Primero, cargaremos nuestro archivo `produccion_2025_1.csv` en un DataFrame de pandas para poder trabajar con él. Luego, mostraremos las primeras filas para entender la estructura de los datos.
"""

import pandas as pd
from ipywidgets import interact, Dropdown, IntSlider
from IPython.display import display

# Ruta del archivo CSV
file_path = '/content/sample_data/produccion_2025_1.csv'

# Cargar los datos en un DataFrame
df = pd.read_csv(file_path)

print("Primeras 5 filas del DataFrame:")
display(df.head())

"""### Paso 2: Exploración Interactiva de Columnas

Podemos usar `ipywidgets` para explorar rápidamente las características de diferentes columnas. Crearemos un widget de menú desplegable que nos permitirá seleccionar una columna y ver su información básica (como el conteo de valores únicos, tipos de datos, etc.).
"""

def explorar_columna(columna):
    print(f"Información para la columna '{columna}':")
    print(df[columna].value_counts() if df[columna].dtype == 'object' else df[columna].describe())

# Crear un widget interactivo con un menú desplegable de columnas
interact(explorar_columna, columna=Dropdown(options=df.columns, description='Selecciona Columna:'));

"""### Paso 3: Filtrado Interactivo de Datos

Ahora, usaremos `ipywidgets` para filtrar el DataFrame de forma interactiva. Por ejemplo, si tenemos una columna categórica como 'product' (asumiendo que existe una columna similar en tu CSV), podemos filtrar los datos para ver solo las filas que pertenecen a un producto específico.
"""

if 'produccion_unidades' in df.columns:
    def filtrar_por_produccion(umbral):
        df_filtrado = df[df['produccion_unidades'] >= umbral]
        print(f"Filas con 'produccion_unidades' mayor o igual a {umbral}:")
        display(df_filtrado.head())
        print(f"Total de filas filtradas: {len(df_filtrado)}")

    # Obtener el rango de valores para el slider
    min_prod = df['produccion_unidades'].min()
    max_prod = df['produccion_unidades'].max()

    # Crear un widget interactivo con un deslizador para filtrar por produccion_unidades
    interact(filtrar_por_produccion, umbral=IntSlider(min=int(min_prod), max=int(max_prod), step=100, value=int(min_prod), description='Min Unidades:'));
else:
    print("La columna 'produccion_unidades' no se encontró en el DataFrame. Por favor, ajusta el nombre de la columna si es diferente.")

"""### Paso 4: Visualización Interactiva (Ejemplo con un control deslizante)

Para hacer una visualización interactiva, podemos crear un gráfico que cambie dinámicamente según la selección de un widget. Por ejemplo, si tenemos una columna numérica como 'cantidad' y una categórica como 'producto', podríamos visualizar la cantidad para diferentes umbrales.
"""

import matplotlib.pyplot as plt

if 'produccion_unidades' in df.columns and 'mes' in df.columns:
    def visualizar_produccion_mes(mes_seleccionado):
        df_filtrado_mes = df[df['mes'] == mes_seleccionado]

        plt.figure(figsize=(10, 6))
        df_filtrado_mes.groupby('turno')['produccion_unidades'].sum().plot(kind='bar')
        plt.title(f'Producción Total por Turno en {mes_seleccionado}')
        plt.xlabel('Turno')
        plt.ylabel('Producción de Unidades')
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.show()

    # Obtener los meses únicos para el menú desplegable
    meses_unicos = df['mes'].unique().tolist()

    # Crear un widget interactivo con un menú desplegable para seleccionar el mes
    interact(visualizar_produccion_mes, mes_seleccionado=Dropdown(options=meses_unicos, description='Selecciona Mes:'));
else:
    print("Las columnas 'produccion_unidades' o 'mes' no se encontraron en el DataFrame. Por favor, ajusta los nombres de las columnas si son diferentes o adapta el ejemplo.")

"""Este tutorial te da una base para empezar a usar `ipywidgets` en tus análisis de datos. Puedes combinar diferentes tipos de widgets y funciones para crear dashboards muy potentes y personalizados en Colab.

### Paso 5: Visualización Interactiva con Gráfico de Pastel

Podemos usar un gráfico de pastel para visualizar la distribución de `produccion_unidades` por diferentes categorías, como el 'turno' o el 'mes'. Usaremos un `Dropdown` para seleccionar la columna categórica y un `IntSlider` para filtrar por un umbral de producción antes de visualizar.
"""

import matplotlib.pyplot as plt

if 'produccion_unidades' in df.columns and 'turno' in df.columns and 'mes' in df.columns:
    def plot_pie_chart(categoria_columna, umbral_produccion):
        # Filtrar el DataFrame basado en el umbral de producción
        df_filtrado_umbral = df[df['produccion_unidades'] >= umbral_produccion]

        if not df_filtrado_umbral.empty:
            # Agrupar por la columna seleccionada y sumar las unidades de producción
            data_para_pastel = df_filtrado_umbral.groupby(categoria_columna)['produccion_unidades'].sum()

            if not data_para_pastel.empty:
                fig, ax = plt.subplots(figsize=(8, 8))
                ax.pie(data_para_pastel, labels=data_para_pastel.index, autopct='%1.1f%%', startangle=90)
                ax.set_title(f'Distribución de Producción de Unidades por {categoria_columna} (Producción >= {umbral_produccion})')
                plt.ylabel('') # Eliminar la etiqueta del eje y para gráficos de pastel
                plt.tight_layout()
                plt.show()
            else:
                print("No hay datos para mostrar en el gráfico de pastel con los filtros seleccionados.")
        else:
            print("No hay datos que cumplan el umbral de producción seleccionado.")

    # Obtener las columnas categóricas relevantes para el gráfico de pastel
    categorical_cols = ['mes', 'turno']

    # Obtener el rango para el control deslizante de umbral de producción
    min_prod_pie = df['produccion_unidades'].min() if not df['produccion_unidades'].empty else 0
    max_prod_pie = df['produccion_unidades'].max() if not df['produccion_unidades'].empty else 100

    # Crear un widget interactivo con un menú desplegable y un deslizador
    interact(plot_pie_chart,
             categoria_columna=Dropdown(options=categorical_cols, description='Agrupar por:'),
             umbral_produccion=IntSlider(min=int(min_prod_pie), max=int(max_prod_pie), step=100, value=int(min_prod_pie), description='Umbral Prod.:'));
else:
    print("Las columnas 'produccion_unidades', 'turno' o 'mes' no se encontraron en el DataFrame. Por favor, ajusta los nombres de las columnas si son diferentes o adapta el ejemplo.")

"""### Paso 6: Visualización Interactiva con Gráfico de Líneas

Para ver tendencias a lo largo del tiempo, un gráfico de líneas es ideal. Podemos usar `ipywidgets` para seleccionar qué columnas queremos visualizar en los ejes X e Y, o para filtrar los datos por alguna categoría antes de graficar la tendencia. Aquí, mostraremos la producción de unidades a lo largo del tiempo ('fecha'), dividida por 'turno'.
"""

import matplotlib.pyplot as plt
import seaborn as sns

if 'fecha' in df.columns and 'produccion_unidades' in df.columns and 'turno' in df.columns:
    # Asegurarse de que la columna 'fecha' sea de tipo datetime
    df['fecha'] = pd.to_datetime(df['fecha'])

    def plot_line_chart(turno_seleccionado):
        # Filtrar el DataFrame por el turno seleccionado
        df_filtrado_turno = df[df['turno'] == turno_seleccionado]

        # Agrupar por fecha y sumar la producción de unidades
        produccion_por_fecha = df_filtrado_turno.groupby('fecha')['produccion_unidades'].sum().reset_index()

        if not produccion_por_fecha.empty:
            fig, ax = plt.subplots(figsize=(12, 6))
            sns.lineplot(x='fecha', y='produccion_unidades', data=produccion_por_fecha, ax=ax)
            ax.set_title(f'Tendencia de Producción de Unidades para el Turno: {turno_seleccionado}')
            ax.set_xlabel('Fecha')
            ax.set_ylabel('Producción de Unidades')
            ax.grid(True, linestyle='--', alpha=0.7)
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()
            plt.show()
        else:
            print(f"No hay datos para el turno '{turno_seleccionado}' para mostrar la tendencia.")

    # Obtener los turnos únicos para el menú desplegable
    turnos_unicos = df['turno'].unique().tolist()

    # Crear un widget interactivo con un menú desplegable para seleccionar el turno
    interact(plot_line_chart, turno_seleccionado=Dropdown(options=turnos_unicos, description='Selecciona Turno:'));
else:
    print("Las columnas 'fecha', 'produccion_unidades' o 'turno' no se encontraron en el DataFrame. Por favor, ajusta los nombres de las columnas si son diferentes o adapta el ejemplo.")

"""Estos ejemplos te muestran cómo puedes utilizar `ipywidgets` para crear dashboards interactivos y explorar tus datos de manera dinámica con diferentes tipos de gráficos. Puedes expandir estos conceptos para incluir más controles, métricas y visualizaciones según tus necesidades."""